"""Public performance page for billybitcoin.cloud/turtlequant/ — stats and HTML.

The page is a static snapshot regenerated by cron (scripts/generate_performance_page.py).
It mirrors the ButterflyGuy page on the same site: server-rendered stats and tables,
chart data in a non-executable <script type="application/json"> block, and one inline
script whose bytes never change between runs. The site's CSP allows that script by
its sha256 hash, so regenerating the numbers must never touch _PAGE_SCRIPT.
"""

# Generated HTML/CSS/JS strings in this module intentionally exceed 100 columns.
# ruff: noqa: E501

from __future__ import annotations

import datetime as dt
import html
import json
import math
from dataclasses import dataclass
from typing import Any

from .history import effective_close_pnl

GITHUB_URL = "https://github.com/hollowc2/turtlequant"
# Crypto markets trade every calendar day, so daily returns annualise over 365.
ANNUALIZATION_DAYS = 365
MODE_LABELS = {
    "shadow": ("Shadow Trading", "Simulated fills against live Polymarket order books"),
    "paper": ("Paper Trading", "Simulated fills against live Polymarket order books"),
    "live": ("Live Trading", "Real orders on the Polymarket CLOB"),
}


@dataclass(frozen=True)
class ClosedTrade:
    market_id: str
    question: str
    asset: str
    option_type: str
    strike: float | None
    expiry: dt.datetime | None
    opened_at: dt.datetime | None
    closed_at: dt.datetime
    entry_price: float | None
    exit_price: float | None
    size_usd: float | None
    edge_at_entry: float | None
    model_prob_at_entry: float | None
    exit_reason: str
    pnl: float
    outcome: str = "YES"  # token held; prices are that token's

    @property
    def return_pct(self) -> float | None:
        return self.pnl / self.size_usd * 100.0 if self.size_usd else None

    @property
    def hold_hours(self) -> float | None:
        if self.opened_at is None:
            return None
        return (self.closed_at - self.opened_at).total_seconds() / 3600.0


@dataclass(frozen=True)
class OpenPosition:
    market_id: str
    question: str
    asset: str
    option_type: str
    strike: float
    expiry: dt.datetime | None
    opened_at: dt.datetime | None
    entry_price: float
    mark_price: float
    size_usd: float
    tokens: float
    edge_at_entry: float
    status: str
    outcome: str = "YES"

    @property
    def unrealized_pnl(self) -> float:
        return (self.mark_price - self.entry_price) * self.tokens


@dataclass(frozen=True)
class Stats:
    starting_nav: float
    ending_nav: float
    total_pnl: float
    return_pct: float
    trade_count: int
    wins: int
    losses: int
    win_rate: float
    profit_factor: float | None  # None when there are no losing trades
    expectancy: float
    avg_win: float | None
    avg_loss: float | None
    payoff_ratio: float | None
    best: float
    worst: float
    max_drawdown_usd: float
    max_drawdown_pct: float
    current_drawdown_pct: float
    sharpe: float | None
    sortino: float | None
    avg_hold_hours: float | None
    max_win_streak: int
    max_loss_streak: int
    avg_edge_at_entry: float | None
    volume_usd: float
    days_tracked: int


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


def parse_ts(value: object) -> dt.datetime | None:
    if not isinstance(value, str) or not value:
        return None
    try:
        parsed = dt.datetime.fromisoformat(value)
    except ValueError:
        return None
    return parsed if parsed.tzinfo else parsed.replace(tzinfo=dt.UTC)


def _opt_float(value: object) -> float | None:
    try:
        result = float(value)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return None
    return result if math.isfinite(result) else None


def build_closed_trades(events: list[dict[str, Any]]) -> list[ClosedTrade]:
    """Pair each close with its open (FIFO per market) into round-trip trades.

    partial_close P&L is carried into the round trip it belongs to, so a trade's
    P&L is everything realised between its open and its final close.
    """
    opens: dict[str, list[dict[str, Any]]] = {}
    partial_pnl: dict[str, float] = {}
    trades: list[ClosedTrade] = []
    for event in events:
        kind = event.get("event")
        market_id = str(event.get("market_id", ""))
        if kind == "open":
            opens.setdefault(market_id, []).append(event)
        elif kind == "partial_close":
            partial_pnl[market_id] = partial_pnl.get(market_id, 0.0) + (_opt_float(event.get("pnl")) or 0.0)
        elif kind == "close":
            closed_at = parse_ts(event.get("ts"))
            if closed_at is None:
                continue
            queue = opens.get(market_id)
            open_event = queue.pop(0) if queue else None
            earlier = partial_pnl.pop(market_id, None)
            if earlier is None:
                pnl = effective_close_pnl(open_event, event)
            else:
                pnl = earlier + (_opt_float(event.get("pnl")) or 0.0)
            opened = open_event or {}
            trades.append(
                ClosedTrade(
                    market_id=market_id,
                    question=str(opened.get("question") or event.get("question") or market_id),
                    asset=str(event.get("asset") or opened.get("asset") or "?").upper(),
                    option_type=str(opened.get("option_type") or "—"),
                    strike=_opt_float(event.get("strike", opened.get("strike"))),
                    expiry=parse_ts(opened.get("expiry")),
                    opened_at=parse_ts(opened.get("ts")),
                    closed_at=closed_at,
                    entry_price=_opt_float(opened.get("yes_price")),
                    exit_price=_opt_float(event.get("yes_price", event.get("exit_price"))),
                    size_usd=_opt_float(opened.get("size_usd")),
                    edge_at_entry=_opt_float(opened.get("edge")),
                    model_prob_at_entry=_opt_float(opened.get("model_prob")),
                    exit_reason=str(event.get("reason") or "—"),
                    pnl=pnl,
                    outcome=str(opened.get("outcome") or event.get("outcome") or "YES"),
                )
            )
    trades.sort(key=lambda t: t.closed_at)
    return trades


def open_positions_from_state(state: dict[str, Any]) -> list[OpenPosition]:
    """Open claims from the positions file, marked like PositionManager.marked_equity."""
    positions: list[OpenPosition] = []
    for raw in state.get("positions") or []:
        if not isinstance(raw, dict):
            continue
        entry = _opt_float(raw.get("entry_price")) or 0.0
        size = _opt_float(raw.get("size_usd")) or 0.0
        if entry <= 0 or size <= 0:
            continue
        status = str(raw.get("status") or "open")
        if status == "pending_redemption" and raw.get("resolution_price") is not None:
            mark = _opt_float(raw.get("resolution_price")) or 0.0
        else:
            mark = (
                _opt_float(raw.get("last_bid"))
                or _opt_float(raw.get("last_yes_price"))
                or entry
            )
        positions.append(
            OpenPosition(
                market_id=str(raw.get("market_id", "")),
                question=str(raw.get("question") or ""),
                asset=str(raw.get("asset") or "?").upper(),
                option_type=str(raw.get("option_type") or "—"),
                strike=_opt_float(raw.get("strike")) or 0.0,
                expiry=parse_ts(raw.get("expiry_iso")),
                opened_at=parse_ts(raw.get("opened_at")),
                entry_price=entry,
                mark_price=mark,
                size_usd=size,
                tokens=_opt_float(raw.get("token_size")) or size / entry,
                edge_at_entry=_opt_float(raw.get("edge_at_entry")) or 0.0,
                status=status,
                outcome=str(raw.get("outcome") or "YES"),
            )
        )
    positions.sort(key=lambda p: p.opened_at or dt.datetime.min.replace(tzinfo=dt.UTC))
    return positions


# ---------------------------------------------------------------------------
# Statistics
# ---------------------------------------------------------------------------


def _longest_streak(pnls: list[float], winning: bool) -> int:
    best = run = 0
    for pnl in pnls:
        if (pnl > 0) if winning else (pnl < 0):
            run += 1
            best = max(best, run)
        else:
            run = 0
    return best


def daily_returns(
    trades: list[ClosedTrade], starting_nav: float, as_of: dt.datetime
) -> list[float]:
    """Realised daily returns on NAV, one per UTC calendar day.

    The window runs from the first trade's open (or close) to as_of, and days with
    no closes count as 0% — leaving them out would overstate Sharpe.
    """
    if not trades or starting_nav <= 0:
        return []
    first = min((t.opened_at or t.closed_at) for t in trades).date()
    last = max(as_of.astimezone(dt.UTC).date(), trades[-1].closed_at.date())
    pnl_by_day: dict[dt.date, float] = {}
    for trade in trades:
        day = trade.closed_at.astimezone(dt.UTC).date()
        pnl_by_day[day] = pnl_by_day.get(day, 0.0) + trade.pnl
    returns: list[float] = []
    equity = starting_nav
    day = first
    while day <= last:
        pnl = pnl_by_day.get(day, 0.0)
        returns.append(pnl / equity if equity > 0 else 0.0)
        equity += pnl
        day += dt.timedelta(days=1)
    return returns


def sharpe_ratio(returns: list[float]) -> float | None:
    if len(returns) < 2:
        return None
    mean = sum(returns) / len(returns)
    var = sum((r - mean) ** 2 for r in returns) / (len(returns) - 1)
    if var <= 0:
        return None
    return mean / math.sqrt(var) * math.sqrt(ANNUALIZATION_DAYS)


def sortino_ratio(returns: list[float]) -> float | None:
    if len(returns) < 2:
        return None
    mean = sum(returns) / len(returns)
    downside = math.sqrt(sum(min(r, 0.0) ** 2 for r in returns) / len(returns))
    if downside <= 0:
        return None
    return mean / downside * math.sqrt(ANNUALIZATION_DAYS)


def equity_series(trades: list[ClosedTrade], starting_nav: float) -> list[dict[str, float]]:
    """NAV, running peak and drawdown after each trade."""
    nav = peak = starting_nav
    points: list[dict[str, float]] = []
    for trade in trades:
        nav += trade.pnl
        peak = max(peak, nav)
        dd_usd = peak - nav
        points.append({
            "nav": nav,
            "peak": peak,
            "dd_usd": dd_usd,
            "dd_pct": dd_usd / peak * 100.0 if peak > 0 else 0.0,
        })
    return points


def compute_stats(
    trades: list[ClosedTrade], starting_nav: float, as_of: dt.datetime
) -> Stats:
    pnls = [t.pnl for t in trades]
    wins = [p for p in pnls if p > 0]
    losses = [p for p in pnls if p < 0]
    total = sum(pnls)
    gross_loss = -sum(losses)
    series = equity_series(trades, starting_nav)
    returns = daily_returns(trades, starting_nav, as_of)
    holds = [h for t in trades if (h := t.hold_hours) is not None]
    edges = [e for t in trades if (e := t.edge_at_entry) is not None]
    avg_win = sum(wins) / len(wins) if wins else None
    avg_loss = sum(losses) / len(losses) if losses else None
    worst_point = max(series, key=lambda p: p["dd_usd"], default=None)
    return Stats(
        starting_nav=starting_nav,
        ending_nav=starting_nav + total,
        total_pnl=total,
        return_pct=total / starting_nav * 100.0 if starting_nav > 0 else 0.0,
        trade_count=len(pnls),
        wins=len(wins),
        losses=len(losses),
        win_rate=len(wins) / len(pnls) * 100.0 if pnls else 0.0,
        profit_factor=sum(wins) / gross_loss if gross_loss > 0 else None,
        expectancy=total / len(pnls) if pnls else 0.0,
        avg_win=avg_win,
        avg_loss=avg_loss,
        payoff_ratio=avg_win / -avg_loss if avg_win is not None and avg_loss else None,
        best=max(pnls, default=0.0),
        worst=min(pnls, default=0.0),
        max_drawdown_usd=worst_point["dd_usd"] if worst_point else 0.0,
        max_drawdown_pct=max((p["dd_pct"] for p in series), default=0.0),
        current_drawdown_pct=series[-1]["dd_pct"] if series else 0.0,
        sharpe=sharpe_ratio(returns),
        sortino=sortino_ratio(returns),
        avg_hold_hours=sum(holds) / len(holds) if holds else None,
        max_win_streak=_longest_streak(pnls, winning=True),
        max_loss_streak=_longest_streak(pnls, winning=False),
        avg_edge_at_entry=sum(edges) / len(edges) if edges else None,
        volume_usd=sum(t.size_usd or 0.0 for t in trades),
        days_tracked=len(returns),
    )


def chart_payload(trades: list[ClosedTrade], starting_nav: float) -> dict[str, Any]:
    rows: list[dict[str, Any]] = []
    for index, (trade, point) in enumerate(zip(trades, equity_series(trades, starting_nav), strict=True)):
        rows.append({
            "index": index + 1,
            "date": trade.closed_at.strftime("%Y-%m-%d"),
            "closed": trade.closed_at.strftime("%Y-%m-%d %H:%M UTC"),
            "asset": trade.asset,
            "question": trade.question[:110],
            "entry": trade.entry_price,
            "exit": trade.exit_price,
            "size": trade.size_usd,
            "hold_h": trade.hold_hours,
            "reason": trade.exit_reason,
            "pnl": trade.pnl,
            "ret": trade.return_pct,
            "nav": point["nav"],
            "peak": point["peak"],
            "dd_usd": point["dd_usd"],
            "dd_pct": point["dd_pct"],
        })
    return {"startNav": starting_nav, "trades": rows}


# ---------------------------------------------------------------------------
# Formatting
# ---------------------------------------------------------------------------

_DASH = "—"


def _usd(value: float | None, *, signed: bool = False, dp: int = 2) -> str:
    if value is None:
        return _DASH
    sign = ("+" if value > 0 else "-" if value < 0 else "") if signed else ("-" if value < 0 else "")
    return f"{sign}${abs(value):,.{dp}f}"


def _pct(value: float | None, *, signed: bool = False, dp: int = 1) -> str:
    if value is None:
        return _DASH
    return f"{value:+.{dp}f}%" if signed and round(value, dp) else f"{value:.{dp}f}%"


def _ratio(value: float | None) -> str:
    return _DASH if value is None else f"{value:.2f}"


def _cents(price: float | None) -> str:
    return _DASH if price is None else f"{price * 100:.1f}¢"


def _hold(hours: float | None) -> str:
    if hours is None:
        return _DASH
    if hours < 48:
        return f"{hours:.1f}h"
    return f"{hours / 24:.1f}d"


def _date(value: dt.datetime | None, fmt: str = "%Y-%m-%d") -> str:
    return _DASH if value is None else value.astimezone(dt.UTC).strftime(fmt)


def _strike(value: float | None) -> str:
    return _DASH if value is None else f"${value:,.0f}"


def _tone(value: float | None) -> str:
    if value is None or value == 0:
        return ""
    return "pos" if value > 0 else "neg"


def _label(text: str) -> str:
    return html.escape(text.replace("_", " "))


def _json_data_block(payload: dict[str, Any]) -> str:
    """Serialise payload for a <script type="application/json"> block.

    Script content is raw text, so the only hazard is a "</script" sequence in the
    data (market questions are third-party text). JSON \\uXXXX escapes for < > &
    remove it while round-tripping through JSON.parse() unchanged.
    """
    encoded = json.dumps(payload, allow_nan=False)
    return encoded.replace("&", "\\u0026").replace("<", "\\u003c").replace(">", "\\u003e")


def _tile(label: str, value: str, *, tone: str = "", sub: str = "") -> str:
    sub_html = f"<div class='sub'>{sub}</div>" if sub else ""
    return (
        f"<div class='stat'><div class='label'>{html.escape(label)}</div>"
        f"<div class='value {tone}'>{value}</div>{sub_html}</div>"
    )


def _cohort_tiles(trades: list[ClosedTrade], key: str) -> str:
    groups: dict[str, list[ClosedTrade]] = {}
    for trade in trades:
        groups.setdefault(getattr(trade, key), []).append(trade)
    tiles = []
    for name, group in sorted(groups.items(), key=lambda item: -len(item[1])):
        pnl = sum(t.pnl for t in group)
        win_rate = sum(1 for t in group if t.pnl > 0) / len(group) * 100.0
        tiles.append(
            _tile(
                name.replace("_", " "),
                f"{len(group)} trade{'' if len(group) == 1 else 's'}",
                sub=f"<span class='{_tone(pnl)}'>{_usd(pnl, signed=True)}</span> · {win_rate:.0f}% win",
            )
        )
    return "".join(tiles) or "<div class='muted-note'>No closed trades yet.</div>"


def _trade_rows(trades: list[ClosedTrade]) -> str:
    rows = []
    for number, trade in reversed(list(enumerate(trades, start=1))):
        outcome = "win" if trade.pnl > 0 else "loss" if trade.pnl < 0 else "flat"
        question = html.escape(trade.question)
        rows.append(
            f"<tr data-outcome='{outcome}'>"
            f"<td>{number}</td>"
            f"<td class='l'>{_date(trade.opened_at, '%Y-%m-%d %H:%M')}</td>"
            f"<td class='l'>{_date(trade.closed_at, '%Y-%m-%d %H:%M')}</td>"
            f"<td>{_hold(trade.hold_hours)}</td>"
            f"<td class='l'>{html.escape(trade.asset)}</td>"
            f"<td class='l market' title='{question}'>{question}</td>"
            f"<td class='l'>{_label(trade.option_type)}</td>"
            f"<td class='l'>{html.escape(trade.outcome)}</td>"
            f"<td>{_strike(trade.strike)}</td>"
            f"<td>{_date(trade.expiry)}</td>"
            f"<td>{_pct(trade.model_prob_at_entry * 100 if trade.model_prob_at_entry is not None else None)}</td>"
            f"<td>{_pct(trade.edge_at_entry * 100 if trade.edge_at_entry is not None else None, signed=True)}</td>"
            f"<td>{_cents(trade.entry_price)}</td>"
            f"<td>{_cents(trade.exit_price)}</td>"
            f"<td>{_usd(trade.size_usd)}</td>"
            f"<td class='l'>{_label(trade.exit_reason)}</td>"
            f"<td class='{_tone(trade.return_pct)}'>{_pct(trade.return_pct, signed=True)}</td>"
            f"<td class='{_tone(trade.pnl)}'>{_usd(trade.pnl, signed=True)}</td>"
            "</tr>"
        )
    if not rows:
        return "<tr><td colspan='18' class='empty-cell'>No closed trades yet.</td></tr>"
    return "".join(rows)


def _open_rows(positions: list[OpenPosition]) -> str:
    rows = []
    for pos in positions:
        question = html.escape(pos.question)
        status = "awaiting redemption" if pos.status == "pending_redemption" else pos.status
        rows.append(
            "<tr>"
            f"<td class='l'>{_date(pos.opened_at, '%Y-%m-%d %H:%M')}</td>"
            f"<td class='l'>{html.escape(pos.asset)}</td>"
            f"<td class='l market' title='{question}'>{question}</td>"
            f"<td class='l'>{_label(pos.option_type)}</td>"
            f"<td class='l'>{html.escape(pos.outcome)}</td>"
            f"<td>{_strike(pos.strike)}</td>"
            f"<td>{_date(pos.expiry)}</td>"
            f"<td>{_pct(pos.edge_at_entry * 100, signed=True)}</td>"
            f"<td>{_cents(pos.entry_price)}</td>"
            f"<td>{_cents(pos.mark_price)}</td>"
            f"<td>{_usd(pos.size_usd)}</td>"
            f"<td class='l'>{html.escape(status)}</td>"
            f"<td class='{_tone(pos.unrealized_pnl)}'>{_usd(pos.unrealized_pnl, signed=True)}</td>"
            "</tr>"
        )
    if not rows:
        return "<tr><td colspan='13' class='empty-cell'>No open positions.</td></tr>"
    return "".join(rows)


# ---------------------------------------------------------------------------
# Chart descriptions (the only thing a screen reader gets for each canvas, so they
# are computed from the same data the charts draw rather than written by hand)
# ---------------------------------------------------------------------------


def equity_description(trades: list[ClosedTrade], stats: Stats) -> str:
    if not trades:
        return f"Line chart of realized NAV. No closed trades yet; NAV is {_usd(stats.starting_nav)}."
    return (
        f"Line chart of realized NAV across {stats.trade_count} closed trades, "
        f"{_date(trades[0].closed_at)} to {_date(trades[-1].closed_at)}. It starts at "
        f"{_usd(stats.starting_nav)} and ends at {_usd(stats.ending_nav)}, "
        f"a return of {_pct(stats.return_pct, signed=True)}. Every trade is listed in the trade log below."
    )


def drawdown_description(stats: Stats) -> str:
    opening = "Line chart of how far realized NAV sits below its running peak, in percent."
    if not stats.trade_count:
        return f"{opening} No closed trades yet."
    return (
        f"{opening} The deepest drawdown is {_pct(stats.max_drawdown_pct)} "
        f"({_usd(stats.max_drawdown_usd)}); the latest reading is {_pct(stats.current_drawdown_pct)}."
    )


def distribution_description(stats: Stats) -> str:
    opening = "Bar chart counting closed trades by percent return on position size."
    if not stats.trade_count:
        return f"{opening} No closed trades yet."
    return (
        f"{opening} {stats.wins} trades won and {stats.losses} lost; the best returned "
        f"{_usd(stats.best, signed=True)} and the worst {_usd(stats.worst, signed=True)}."
    )


# ---------------------------------------------------------------------------
# Page
# ---------------------------------------------------------------------------


def render_page(
    *,
    trades: list[ClosedTrade],
    open_positions: list[OpenPosition],
    starting_nav: float,
    generated_at: dt.datetime,
    mode: str = "shadow",
) -> str:
    badge, mode_note = MODE_LABELS[mode]
    stats = compute_stats(trades, starting_nav, generated_at)
    data_block = _json_data_block(chart_payload(trades, starting_nav))
    stamp = generated_at.astimezone(dt.UTC).strftime("%Y-%m-%d %H:%M UTC")
    through = f" · through {_date(trades[-1].closed_at)}" if trades else ""
    exposure = sum(p.size_usd for p in open_positions)
    unrealized = sum(p.unrealized_pnl for p in open_positions)

    headline = "".join([
        _tile("Total P&L", _usd(stats.total_pnl, signed=True), tone=_tone(stats.total_pnl)),
        _tile("Return", _pct(stats.return_pct, signed=True), tone=_tone(stats.return_pct), sub=f"on {_usd(stats.starting_nav, dp=0)} start"),
        _tile("NAV", _usd(stats.ending_nav), sub="realized"),
        _tile("Win Rate", _pct(stats.win_rate, dp=0), sub=f"{stats.wins}W · {stats.losses}L"),
        _tile("Profit Factor", "∞" if stats.profit_factor is None and stats.wins else _ratio(stats.profit_factor)),
        _tile("Sharpe", _ratio(stats.sharpe), sub="annualized, daily"),
        _tile("Max Drawdown", _pct(stats.max_drawdown_pct), tone="neg" if stats.max_drawdown_pct else "", sub=_usd(stats.max_drawdown_usd)),
    ])
    metrics = "".join([
        _tile("Closed Trades", str(stats.trade_count), sub=f"over {stats.days_tracked} days"),
        _tile("Expectancy", _usd(stats.expectancy, signed=True), tone=_tone(stats.expectancy), sub="per trade"),
        _tile("Avg Win", _usd(stats.avg_win, signed=True), tone="pos" if stats.avg_win else ""),
        _tile("Avg Loss", _usd(stats.avg_loss, signed=True), tone="neg" if stats.avg_loss else ""),
        _tile("Payoff Ratio", _ratio(stats.payoff_ratio), sub="avg win / avg loss"),
        _tile("Best Trade", _usd(stats.best, signed=True), tone=_tone(stats.best)),
        _tile("Worst Trade", _usd(stats.worst, signed=True), tone=_tone(stats.worst)),
        _tile("Sortino", _ratio(stats.sortino), sub="annualized, daily"),
        _tile("Avg Hold", _hold(stats.avg_hold_hours)),
        _tile("Win Streak", str(stats.max_win_streak), sub="longest"),
        _tile("Loss Streak", str(stats.max_loss_streak), sub="longest"),
        _tile("Avg Entry Edge", _pct(stats.avg_edge_at_entry * 100 if stats.avg_edge_at_entry is not None else None, signed=True), sub="model − price"),
        _tile("Volume", _usd(stats.volume_usd, dp=0), sub="entry notional"),
    ])
    open_tiles = "".join([
        _tile("Open Positions", str(len(open_positions))),
        _tile("Exposure", _usd(exposure), sub=_pct(exposure / stats.ending_nav * 100 if stats.ending_nav > 0 else None) + " of NAV"),
        _tile("Unrealized P&L", _usd(unrealized, signed=True), tone=_tone(unrealized), sub="mark to bid"),
    ])

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>TurtleQuant — Polymarket Performance</title>
  <meta name="description" content="TurtleQuant prices Polymarket crypto markets as digital options and trades the edge. Equity curve, drawdown, return distribution and every trade.">
  <link rel="preload" as="font" type="font/woff2" crossorigin href="/assets/fonts/inter-var-latin.woff2">
  <link rel="stylesheet" href="/assets/fonts.css">
  <script src="/assets/vendor/chart.umd.min.js"></script>
  <style>{_BASE_CSS}</style>
</head>
<body>
<main>
  <nav class="top-links">
    <a class="site-link" href="/"><span aria-hidden="true">←</span>billybitcoin.cloud</a>
    <a class="site-link" href="{GITHUB_URL}" target="_blank" rel="noopener noreferrer">source on GitHub<span aria-hidden="true">↗</span></a>
  </nav>

  <header class="hero">
    <h1>TurtleQuant — Polymarket Performance</h1>
    <p class="about">
      Prices Polymarket crypto markets ("Will BTC be above $X by date?") as digital and barrier
      options — Black-Scholes with Deribit implied volatility — and buys when the model probability
      clears the executable ask by a margin. Sized with fractional Kelly under per-market and total
      exposure caps.
    </p>
    <div class="sub">
      <span class="badge">{html.escape(badge)}</span>
      {html.escape(mode_note)} · {stats.trade_count} closed trades{through} · Regenerated hourly, last built {html.escape(stamp)}
    </div>
  </header>

  <section class="stats">{headline}</section>

  <h2>Equity Curve</h2>
  <section class="panel chart-panel">
    <canvas id="equityChart" height="120" role="img" aria-label="{html.escape(equity_description(trades, stats))}"></canvas>
    <div class="chart-legend" aria-hidden="true">
      <span class="legend-item"><span class="legend-dot legend-dot-win"></span> Winning trade</span>
      <span class="legend-item"><span class="legend-dot legend-dot-loss"></span> Losing trade</span>
    </div>
  </section>

  <h2>Drawdown from Peak NAV</h2>
  <section class="panel chart-panel">
    <canvas id="drawdownChart" height="90" role="img" aria-label="{html.escape(drawdown_description(stats))}"></canvas>
    <p class="chart-note"><b id="drawdownNoteFigures"></b> Measured on realized NAV (starting capital plus closed-trade P&amp;L); open positions are not marked into this curve.</p>
  </section>

  <h2>Return Distribution</h2>
  <section class="panel chart-panel">
    <div class="chart-tools">
      <div class="segmented" role="group" aria-label="Bucket size">
        <button type="button" class="bucket-control" data-bucket="5">5%</button>
        <button type="button" class="bucket-control active" data-bucket="10">10%</button>
        <button type="button" class="bucket-control" data-bucket="25">25%</button>
      </div>
      <label class="toggle"><input type="checkbox" id="fitCurveToggle" checked> Fit curve</label>
    </div>
    <canvas id="returnDistributionChart" height="95" role="img" aria-label="{html.escape(distribution_description(stats))}"></canvas>
    <p class="chart-note">Return per trade as a percentage of the dollars put into the position, net of fees.</p>
  </section>

  <h2>Trade Metrics</h2>
  <section class="stats">{metrics}</section>

  <h2>By Exit Reason</h2>
  <section class="stats cohorts">{_cohort_tiles(trades, "exit_reason")}</section>

  <h2>By Asset</h2>
  <section class="stats cohorts">{_cohort_tiles(trades, "asset")}</section>

  <h2>Open Positions</h2>
  <section class="stats cohorts">{open_tiles}</section>
  <section class="panel table-panel">
    <table>
      <thead>
        <tr>
          <th class="l">Opened (UTC)</th><th class="l">Asset</th><th class="l">Market</th><th class="l">Type</th>
          <th class="l">Side</th><th>Strike</th><th>Expiry</th><th>Edge</th><th>Entry</th><th>Mark</th><th>Size</th>
          <th class="l">Status</th><th>Unrealized</th>
        </tr>
      </thead>
      <tbody>{_open_rows(open_positions)}</tbody>
    </table>
  </section>

  <details class="panel trade-log-panel" open>
    <summary class="section-summary">
      <span>Trade Log</span>
      <span class="summary-meta">{stats.trade_count} trades · newest first</span>
    </summary>
    <div class="table-tools">
      <div class="segmented" role="group" aria-label="Filter trades">
        <button type="button" class="outcome-control active" data-outcome="all">All</button>
        <button type="button" class="outcome-control" data-outcome="win">Winners</button>
        <button type="button" class="outcome-control" data-outcome="loss">Losers</button>
      </div>
    </div>
    <div class="table-scroll">
      <table>
        <thead>
          <tr>
            <th>#</th><th class="l">Opened (UTC)</th><th class="l">Closed (UTC)</th><th>Hold</th>
            <th class="l">Asset</th><th class="l">Market</th><th class="l">Type</th><th class="l">Side</th>
            <th>Strike</th><th>Expiry</th>
            <th>Model P</th><th>Edge</th><th>Entry</th><th>Exit</th><th>Size</th>
            <th class="l">Exit Reason</th><th>Return</th><th>P&amp;L</th>
          </tr>
        </thead>
        <tbody>{_trade_rows(trades)}</tbody>
      </table>
    </div>
  </details>

  <section class="methodology">
    <h2>Methodology</h2>
    <ul>
      <li>P&amp;L is realized and net of modeled taker fees. Entry and exit prices are the held token's prices (YES or NO, see Side) in cents.</li>
      <li>Sharpe and Sortino are annualized (√365) from daily returns on realized NAV. Days with no closed trades count as 0%.</li>
      <li>Edge is model probability minus the executable ask at entry. Open-position marks use the last observed best bid, before exit fees; resolved markets use the resolution price.</li>
      <li>Profit factor is gross winning P&amp;L over gross losing P&amp;L. Payoff ratio is average win over average loss.</li>
    </ul>
  </section>
</main>
<!-- Generator-emitted data. Kept in a non-executable application/json block so
     the CSP hash of the script below stays stable when the numbers change. -->
<script type="application/json" id="chart-data">
{data_block}
</script>
<script>{_PAGE_SCRIPT}</script>
</body>
</html>
"""


# Plain string, not an f-string: its bytes are hashed into the site's CSP and must
# be identical on every run. Only the JSON data block above varies.
_PAGE_SCRIPT = r"""
const payload = JSON.parse(document.getElementById('chart-data').textContent);
const trades = payload.trades;
const startNav = payload.startNav;

const UP = '#6aaa78';
const DOWN = '#cc5555';
const ACCENT = '#c8922a';
const TEXT = '#e8e2d6';
const MUTED = '#948d87';
const GRID = 'rgba(232,226,214,0.06)';

const signed = (v, dp = 2) => `${v > 0 ? '+' : v < 0 ? '-' : ''}$${Math.abs(v).toLocaleString('en-US', { minimumFractionDigits: dp, maximumFractionDigits: dp })}`;
const cents = (p) => (p == null ? '—' : `${(p * 100).toFixed(1)}¢`);
const hold = (h) => (h == null ? '—' : h < 48 ? `${h.toFixed(1)}h` : `${(h / 24).toFixed(1)}d`);

const labels = ['Start', ...trades.map((d) => d.date)];
const navValues = [startNav, ...trades.map((d) => d.nav)];
const pointColors = [MUTED, ...trades.map((d) => (d.pnl >= 0 ? UP : DOWN))];
const drawdownValues = [0, ...trades.map((d) => -d.dd_pct)];
const deepest = drawdownValues.length > 1 ? drawdownValues.indexOf(Math.min(...drawdownValues)) : -1;
const deepestMarker = drawdownValues.map((v, i) => (i === deepest && v < 0 ? v : null));
const returnValues = trades.filter((d) => d.ret != null).map((d) => d.ret);

const tradeAt = (i) => (i > 0 ? trades[i - 1] : null);

const chartDefaults = {
  responsive: true,
  maintainAspectRatio: true,
  interaction: { mode: 'index', intersect: false },
  plugins: {
    legend: { display: false },
    tooltip: {
      backgroundColor: '#161616',
      borderColor: 'rgba(232,226,214,0.15)',
      borderWidth: 1,
      titleColor: TEXT,
      bodyColor: TEXT,
      padding: 12,
    },
  },
  scales: {
    x: {
      ticks: { color: MUTED, maxRotation: 0, autoSkip: true, maxTicksLimit: 12 },
      grid: { color: GRID },
    },
  },
};

function withTooltip(body, title) {
  return {
    ...chartDefaults.plugins,
    tooltip: {
      ...chartDefaults.plugins.tooltip,
      callbacks: { title, label: () => '', afterBody: body },
    },
  };
}

function equityTooltip(items) {
  if (!items.length) return [];
  const d = tradeAt(items[0].dataIndex);
  if (!d) return [`Starting NAV: $${startNav.toFixed(2)}`];
  return [
    `#${d.index} · ${d.asset} · ${d.reason.replace(/_/g, ' ')}`,
    d.question,
    `Entry ${cents(d.entry)} → Exit ${cents(d.exit)} · held ${hold(d.hold_h)}`,
    `Trade P&L: ${signed(d.pnl)}${d.ret != null ? ` (${d.ret >= 0 ? '+' : ''}${d.ret.toFixed(1)}%)` : ''}`,
    `NAV: $${d.nav.toFixed(2)}`,
  ];
}

function drawdownTooltip(items) {
  if (!items.length) return [];
  const d = tradeAt(items[0].dataIndex);
  if (!d) return ['Start'];
  return [
    `Drawdown: ${d.dd_pct.toFixed(2)}% (${signed(-d.dd_usd)})`,
    `NAV: $${d.nav.toFixed(2)} · Peak: $${d.peak.toFixed(2)}`,
  ];
}

const titleFor = (items) => {
  if (!items.length) return '';
  const d = tradeAt(items[0].dataIndex);
  return d ? d.closed : 'Start';
};

new Chart(document.getElementById('equityChart'), {
  type: 'line',
  data: {
    labels,
    datasets: [{
      label: 'NAV',
      data: navValues,
      borderColor: ACCENT,
      backgroundColor: 'rgba(200,146,42,0.08)',
      pointBackgroundColor: pointColors,
      pointBorderColor: pointColors,
      pointRadius: trades.length > 150 ? 2 : 4,
      pointHoverRadius: 7,
      borderWidth: 2,
      tension: 0.15,
      fill: true,
    }],
  },
  options: {
    ...chartDefaults,
    plugins: withTooltip(equityTooltip, titleFor),
    scales: {
      ...chartDefaults.scales,
      y: { ticks: { color: MUTED, callback: (v) => `$${v}` }, grid: { color: GRID } },
    },
  },
});

new Chart(document.getElementById('drawdownChart'), {
  type: 'line',
  data: {
    labels,
    datasets: [
      {
        label: 'Drawdown %',
        data: drawdownValues,
        borderColor: DOWN,
        backgroundColor: 'rgba(204,85,85,0.25)',
        pointRadius: 0,
        borderWidth: 1.5,
        fill: true,
        stepped: true,
      },
      {
        label: 'Deepest drawdown',
        data: deepestMarker,
        showLine: false,
        borderColor: TEXT,
        backgroundColor: DOWN,
        pointRadius: 5,
        pointHoverRadius: 5,
        pointBorderWidth: 1.5,
      },
    ],
  },
  options: {
    ...chartDefaults,
    plugins: {
      ...withTooltip(drawdownTooltip, titleFor),
      tooltip: { ...withTooltip(drawdownTooltip, titleFor).tooltip, filter: (item) => item.datasetIndex === 0 },
    },
    scales: {
      ...chartDefaults.scales,
      y: { max: 0, ticks: { color: MUTED, callback: (v) => `${v}%` }, grid: { color: GRID } },
    },
  },
});

const deepestTrade = tradeAt(deepest);
const drawdownNote = document.getElementById('drawdownNoteFigures');
if (drawdownNote && deepestTrade && deepestTrade.dd_pct > 0) {
  drawdownNote.textContent = `Marked point: the deepest drawdown, ${deepestTrade.dd_pct.toFixed(2)}% `
    + `(${signed(-deepestTrade.dd_usd)}) on ${deepestTrade.date}, from a peak NAV of $${deepestTrade.peak.toFixed(2)}.`;
}

function buildReturnDistribution(bucketSize) {
  if (!returnValues.length) return { labels: [], counts: [], curve: [], buckets: [] };
  const minBucket = Math.floor(Math.min(...returnValues) / bucketSize) * bucketSize;
  const maxBucket = Math.floor(Math.max(...returnValues) / bucketSize) * bucketSize;
  const buckets = [];
  for (let start = minBucket; start <= maxBucket; start += bucketSize) {
    buckets.push({ start, end: start + bucketSize, count: 0, pnl: 0 });
  }
  trades.forEach((d) => {
    if (d.ret == null) return;
    const index = Math.max(0, Math.min(buckets.length - 1,
      Math.round((Math.floor(d.ret / bucketSize) * bucketSize - minBucket) / bucketSize)));
    buckets[index].count += 1;
    buckets[index].pnl += d.pnl;
  });
  const counts = buckets.map((b) => b.count);
  const maxCount = Math.max(...counts, 1);
  const mean = returnValues.reduce((s, v) => s + v, 0) / returnValues.length;
  const std = Math.sqrt(returnValues.reduce((s, v) => s + (v - mean) ** 2, 0) / returnValues.length) || bucketSize;
  const raw = buckets.map((b) => Math.exp(-0.5 * (((b.start + bucketSize / 2) - mean) / std) ** 2));
  const maxRaw = Math.max(...raw, 1e-9);
  return {
    labels: buckets.map((b) => `${b.start}% to ${b.end}%`),
    counts,
    curve: raw.map((v) => (v / maxRaw) * maxCount),
    buckets,
  };
}

const bucketFill = (b) => (b.end <= 0 ? 'rgba(204,85,85,0.55)' : b.start >= 0 ? 'rgba(106,170,120,0.55)' : 'rgba(200,146,42,0.55)');
const bucketBorder = (b) => (b.end <= 0 ? DOWN : b.start >= 0 ? UP : ACCENT);

let bucketSize = 10;
let showFit = true;
let distribution = buildReturnDistribution(bucketSize);

const distributionChart = new Chart(document.getElementById('returnDistributionChart'), {
  type: 'bar',
  data: {
    labels: distribution.labels,
    datasets: [
      {
        type: 'bar',
        label: 'Trades',
        data: distribution.counts,
        backgroundColor: distribution.buckets.map(bucketFill),
        borderColor: distribution.buckets.map(bucketBorder),
        borderWidth: 1,
        borderRadius: 4,
      },
      {
        type: 'line',
        label: 'Fit curve',
        data: distribution.curve,
        borderColor: TEXT,
        backgroundColor: 'transparent',
        pointRadius: 0,
        borderWidth: 2,
        tension: 0.35,
        hidden: !showFit,
      },
    ],
  },
  options: {
    ...chartDefaults,
    plugins: withTooltip(
      (items) => {
        if (!items.length) return [];
        const b = distribution.buckets[items[0].dataIndex];
        return [`${b.count} trade${b.count === 1 ? '' : 's'}`, `Bucket P&L: ${signed(b.pnl)}`];
      },
      (items) => (items.length ? distribution.labels[items[0].dataIndex] : ''),
    ),
    scales: {
      ...chartDefaults.scales,
      y: { beginAtZero: true, ticks: { color: MUTED, precision: 0 }, grid: { color: GRID } },
    },
  },
});

function updateDistribution() {
  distribution = buildReturnDistribution(bucketSize);
  distributionChart.data.labels = distribution.labels;
  distributionChart.data.datasets[0].data = distribution.counts;
  distributionChart.data.datasets[0].backgroundColor = distribution.buckets.map(bucketFill);
  distributionChart.data.datasets[0].borderColor = distribution.buckets.map(bucketBorder);
  distributionChart.data.datasets[1].data = distribution.curve;
  distributionChart.data.datasets[1].hidden = !showFit;
  distributionChart.update();
}

function activate(selector, button) {
  document.querySelectorAll(selector).forEach((item) => {
    item.classList.toggle('active', item === button);
    item.setAttribute('aria-pressed', String(item === button));
  });
}

document.querySelectorAll('.bucket-control').forEach((button) => {
  button.addEventListener('click', () => {
    bucketSize = Number(button.dataset.bucket);
    activate('.bucket-control', button);
    updateDistribution();
  });
});

document.getElementById('fitCurveToggle').addEventListener('change', (event) => {
  showFit = event.target.checked;
  updateDistribution();
});

document.querySelectorAll('.outcome-control').forEach((button) => {
  button.addEventListener('click', () => {
    const outcome = button.dataset.outcome;
    activate('.outcome-control', button);
    document.querySelectorAll('tr[data-outcome]').forEach((row) => {
      row.hidden = outcome !== 'all' && row.dataset.outcome !== outcome;
    });
  });
});
"""


_BASE_CSS = """
:root {
  color-scheme: dark;
  --bg: #0c0c0c;
  --panel: #121212;
  --text: #e8e2d6;
  --accent: #c8922a;
  /* Same palette as /butterfly-spx/: --muted clears WCAG AA (5.98:1 on --bg,
     5.73:1 on panels) and --down is lifted to #d66a6a for AA on 13px cells;
     chart strokes keep the deeper #cc5555 (graphics only need 3:1). */
  --muted: #948d87;
  --border: rgba(232, 226, 214, 0.1);
  --up: #6aaa78;
  --down: #d66a6a;
  font-family: Inter, ui-sans-serif, system-ui, sans-serif;
  background: var(--bg);
  color: var(--text);
}
body { margin: 0; background: var(--bg); }
main { max-width: 1320px; margin: 0 auto; padding: 28px 24px 48px; }
:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }
.top-links { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 20px; }
.site-link {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 6px 13px 6px 11px;
  background: var(--panel);
  border: 1px solid var(--border);
  border-radius: 999px;
  color: var(--muted);
  font-family: "IBM Plex Mono", ui-monospace, monospace;
  font-size: 12px;
  letter-spacing: 0.02em;
  text-decoration: none;
  transition: color 120ms ease, border-color 120ms ease;
}
.site-link:hover, .site-link:focus-visible { color: var(--text); border-color: rgba(200, 146, 42, 0.45); }
.site-link span { color: var(--accent); }
h1 { font-size: 28px; margin: 0 0 8px; font-weight: 600; }
h2 { font-size: 15px; margin: 28px 0 10px; color: var(--muted); font-weight: 500; text-transform: uppercase; letter-spacing: 0.04em; }
.about { max-width: 78ch; margin: 0 0 12px; color: var(--text); opacity: 0.85; font-size: 14.5px; line-height: 1.55; }
.sub { color: var(--muted); font-size: 14px; }
.stat .sub { font-size: 12px; margin-top: 4px; }
.badge {
  display: inline-block;
  background: rgba(200, 146, 42, 0.15);
  color: var(--accent);
  border: 1px solid rgba(200, 146, 42, 0.35);
  border-radius: 999px;
  padding: 2px 10px;
  font-size: 12px;
  margin-right: 8px;
}
/* Wrapping flex rather than a fixed grid: tiles left on the final row grow to fill
   it, so any tile count reads as deliberate at every viewport. */
.stats { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 22px; }
h2 + .stats { margin-top: 0; }
.stat { box-sizing: border-box; flex: 1 1 140px; background: var(--panel); border: 1px solid var(--border); border-radius: 10px; padding: 14px; }
.cohorts .stat { max-width: 240px; }
.label { color: var(--muted); font-size: 12px; }
.value { font-family: "IBM Plex Mono", ui-monospace, monospace; font-size: 20px; font-weight: 500; margin-top: 6px; }
.muted-note { color: var(--muted); font-size: 13px; padding: 4px 2px; }
.panel { background: var(--panel); border: 1px solid var(--border); border-radius: 10px; padding: 14px; }
.chart-panel { min-height: 220px; }
.table-panel, .table-scroll { overflow-x: auto; }
.table-panel { margin-top: 10px; }
.chart-tools { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 10px; }
.chart-legend { display: flex; flex-wrap: wrap; gap: 14px; margin-top: 10px; color: var(--muted); font-size: 12px; }
.legend-item { display: inline-flex; align-items: center; gap: 7px; }
.legend-dot { display: inline-block; width: 9px; height: 9px; border-radius: 999px; }
.legend-dot-win { background: #6aaa78; }
.legend-dot-loss { background: #cc5555; }
.segmented { display: inline-flex; gap: 2px; padding: 3px; background: #0f0f0f; border: 1px solid var(--border); border-radius: 8px; }
.bucket-control, .outcome-control {
  color: var(--muted);
  background: transparent;
  border: 0;
  border-radius: 6px;
  padding: 7px 11px;
  font-family: "IBM Plex Mono", ui-monospace, monospace;
  font-size: 12px;
  cursor: pointer;
}
.bucket-control.active, .outcome-control.active { color: var(--text); background: rgba(200, 146, 42, 0.18); }
.toggle { color: var(--muted); display: inline-flex; align-items: center; gap: 7px; font-size: 13px; }
.toggle input { accent-color: var(--accent); }
.trade-log-panel { margin-top: 28px; padding-top: 10px; }
.section-summary {
  list-style: none;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  font-size: 15px;
  color: var(--muted);
  text-transform: uppercase;
  letter-spacing: 0.04em;
  user-select: none;
}
.section-summary::-webkit-details-marker { display: none; }
/* The arrow hangs off the title span, not the summary: as a direct flex child it
   would become a third item and space-between would centre the title. */
.section-summary > span:first-child::before { content: "▾"; color: var(--accent); font-size: 13px; margin-right: 8px; }
.trade-log-panel:not([open]) .section-summary > span:first-child::before { content: "▸"; }
.section-summary > span:first-child { display: inline-flex; align-items: center; }
.summary-meta { color: var(--muted); font-size: 12px; text-transform: none; letter-spacing: 0; }
.table-tools { display: flex; justify-content: flex-end; margin: 12px 0 10px; }
table { width: 100%; border-collapse: collapse; font-size: 13px; white-space: nowrap; }
th, td { border-bottom: 1px solid var(--border); padding: 8px 10px; text-align: right; }
th { color: var(--muted); font-size: 11px; text-transform: uppercase; letter-spacing: 0.03em; background: #0f0f0f; position: sticky; top: 0; }
th.l, td.l { text-align: left; }
td.market { max-width: 340px; overflow: hidden; text-overflow: ellipsis; }
td.empty-cell { text-align: center; color: var(--muted); padding: 28px; }
.pos { color: var(--up); font-weight: 600; }
.neg { color: var(--down); font-weight: 600; }
.chart-note { margin: 12px 2px 0; max-width: 80ch; color: var(--muted); font-size: 12.5px; line-height: 1.55; }
.chart-note b { color: var(--text); font-weight: 500; }
.methodology ul { margin: 0; padding-left: 18px; color: var(--muted); font-size: 13px; line-height: 1.6; max-width: 90ch; }
@media (max-width: 980px) {
  main { padding: 16px; }
  .cohorts .stat { max-width: none; }
}
"""
